#include "types.h"

namespace esphome {
namespace geometrie_camera_app {

ImagePoint::ImagePoint() : x(0.0f), y(0.0f) {}

ImageLine::ImageLine()
    : valid(false), point(), dx(0.0f), dy(0.0f) {}

CameraCalibration::CameraCalibration()
    : fx_px(0.0f),
      fy_px(0.0f),
      cx_px(0.0f),
      cy_px(0.0f),
      k1(0.0f),
      k2(0.0f),
      p1(0.0f),
      p2(0.0f),
      k3(0.0f),
      reference_width_px(0),
      reference_height_px(0) {}

TargetObservation::TargetObservation()
    : valid(false),
      center_x_px(0.0f),
      center_y_px(0.0f),
      width_px(0.0f),
      height_px(0.0f),
      rotation_deg(0.0f),
      quality(0.0f),
      subpixel_refined(false),
      subpixel_rms_px(0.0f),
      subpixel_max_rms_px(0.0f),
      subpixel_gradient(0.0f),
      subpixel_width_px(0.0f),
      subpixel_height_px(0.0f),
      subpixel_width_sigma_px(0.0f),
      subpixel_height_sigma_px(0.0f),
      subpixel_width_gradient(0.0f),
      subpixel_height_gradient(0.0f),
      subpixel_v5_width_px(0.0f),
      subpixel_v5_height_px(0.0f),
      subpixel_v5_width_sigma_px(0.0f),
      subpixel_v5_height_sigma_px(0.0f),
      subpixel_v6_width_px(0.0f),
      subpixel_v6_height_px(0.0f),
      subpixel_v6_width_sigma_px(0.0f),
      subpixel_v6_height_sigma_px(0.0f),
      subpixel_top_rms_px(0.0f),
      subpixel_right_rms_px(0.0f),
      subpixel_bottom_rms_px(0.0f),
      subpixel_left_rms_px(0.0f),
      subpixel_top_gradient(0.0f),
      subpixel_right_gradient(0.0f),
      subpixel_bottom_gradient(0.0f),
      subpixel_left_gradient(0.0f),
      subpixel_top_line(),
      subpixel_right_line(),
      subpixel_bottom_line(),
      subpixel_left_line(),
      top_left_px(),
      top_right_px(),
      bottom_right_px(),
      bottom_left_px() {}

GeometryMeasurement::GeometryMeasurement()
    : valid(false),
      calibrated(false),
      pose_valid(false),
      pose_v1_valid(false),
      pose_v2_valid(false),
      pose_v2_used(false),
      edge_v4_used(false),
      edge_v5_used(false),
      edge_v6_used(false),
      apparent_width_px(0.0f),
      apparent_height_px(0.0f),
      apparent_width_sigma_px(0.0f),
      apparent_height_sigma_px(0.0f),
      corner_width_px(0.0f),
      corner_height_px(0.0f),
      v5_width_px(0.0f),
      v5_height_px(0.0f),
      v6_width_px(0.0f),
      v6_height_px(0.0f),
      v61_width_px(0.0f),
      v61_height_px(0.0f),
      v5_v6_width_delta_px(0.0f),
      v5_v6_height_delta_px(0.0f),
      v5_z_mm(0.0f),
      v6_z_mm(0.0f),
      v61_z_mm(0.0f),
      edge_top_rms_px(0.0f),
      edge_right_rms_px(0.0f),
      edge_bottom_rms_px(0.0f),
      edge_left_rms_px(0.0f),
      edge_top_gradient(0.0f),
      edge_right_gradient(0.0f),
      edge_bottom_gradient(0.0f),
      edge_left_gradient(0.0f),
      width_distance_weight(0.5f),
      height_distance_weight(0.5f),
      distance_mm(0.0f),
      x_mm(0.0f),
      y_mm(0.0f),
      z_mm(0.0f),
      z_from_width_mm(0.0f),
      z_from_height_mm(0.0f),
      bearing_yaw_deg(0.0f),
      bearing_pitch_deg(0.0f),
      yaw_deg(0.0f),
      pitch_deg(0.0f),
      roll_deg(0.0f),
      pose_v1_yaw_deg(0.0f),
      pose_v1_pitch_deg(0.0f),
      pose_v1_roll_deg(0.0f),
      pose_v2_yaw_deg(0.0f),
      pose_v2_pitch_deg(0.0f),
      pose_v2_roll_deg(0.0f),
      pose_v2_line_rms_px(0.0f),
      pose_v2_corner_rms_px(0.0f),
      pose_normal_x(0.0f),
      pose_normal_y(0.0f),
      pose_normal_z(0.0f),
      pose_z_mm(0.0f),
      pose_scale_error_pct(0.0f),
      quality(0.0f),
      timestamp_ms(0) {}

GrayFrameView::GrayFrameView()
    : data(nullptr), width(0), height(0), stride(0) {}

}  // namespace geometrie_camera_app
}  // namespace esphome
